### ISSUE TITLE
Image error on Officer pages

### ISSUE THREAD

**Issue by kimricher** [mshappe/ruby-the-gryphon#23]
![officer tag](https://user-images.githubusercontent.com/43527863/46576935-797bb900-c99d-11e8-8b30-e82cddf86b10.jpg)

**Comment by mshappe** [comment]
The actual issue here is that I am not providing alt text, and the Rails `image_tag` defaults to the most "local" part of the image URL. The image itself is not rendering for some reason (conversion problem? Those WERE working at one time, and some pictures clearly are), so we're seeing the broken-image icon and weird alt-text. I will see if I can do something smarter, or better yet, see why the image isn't rendering right.
